<?php
header('Content-Type: application/json');

$userInput = isset($_GET['userInput']) ? trim($_GET['userInput']) : '';

// First, check responses.txt for known responses.
if (file_exists('responses.txt')) {
    $responses = file('responses.txt', FILE_IGNORE_NEW_LINES);
    foreach ($responses as $line) {
        // Look for a line that starts with the question followed by a colon.
        if (strpos($line, $userInput . ":") === 0) {
            $reply = substr($line, strlen($userInput) + 2);
            echo json_encode(["type" => "bot", "reply" => $reply]);
            exit;
        }
    }
}

// If not found in responses.txt, check the database.
$mysqli = new mysqli("localhost", "root", "", "EduAssistaDB");
if ($mysqli->connect_error) {
    echo json_encode(["type" => "error", "reply" => "Database connection error."]);
    exit;
}

$stmt = $mysqli->prepare("SELECT Reply, Email FROM questions WHERE QuestionText = ? AND Reply <> '' ORDER BY Date DESC LIMIT 1");
$stmt->bind_param("s", $userInput);
$stmt->execute();
$stmt->bind_result($reply, $replyEmail);
if ($stmt->fetch()) {
    if (!empty($replyEmail)) {
        // Reply provided by support.
        echo json_encode(["type" => "support", "reply" => $reply]);
    } else {
        // Reply generated by the bot.
        echo json_encode(["type" => "bot", "reply" => $reply]);
    }
} else {
    echo json_encode(["type" => "unknown", "reply" => "unknown"]);
}
$stmt->close();
$mysqli->close();
?>
